Hotfix/readme corrections
itk-dev/ddb-cover-service pull request #4
Opened 2019-11-26 06:14 UTC by tuj

* Fixed issue with schema not validating.
* Fixed issue with fixtures not being able to run.
* Minor text fixes.
* Applied coding standards.

2019-11-26 18:45 UTC, turegjorup requested changes
1.
I don't consider this a hotfix. Hotfixes are solely for fixing critical bugs in productions: https://nvie.com/posts/a-successful-git-branching-model/#hotfix-branches

2.
Did you get the fixtures to run using the supplied command? I get an error related to https://github.com/doctrine/data-fixtures/pull/127 because of the `--purge-with-truncate` flag

2019-11-26 18:45 UTC, turegjorup commented on README.md
> +   working. Run `bin/console fos:elastica:create --env=test` to create the test index.
This is not necessary. ES indexes are reset by `resetIndex()`in the `FeatureContext`: https://github.com/itk-dev/ddb-cover-service/blob/99575b4f962c31480372f3f1edee49ffae61f076/features/bootstrap/FeatureContext.php#L144

2019-11-26 18:45 UTC, turegjorup commented on README.md
>  4. Run migrations `bin/console doctrine:migrations:migrate`
Step 3 should be removed. The docker setup pre-creates the database

2019-11-27 14:30 UTC, cableman approved these changes

2019-11-27 20:09 UTC, merged